/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE DATABASE IF NOT EXISTS `directorio` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `directorio`;

CREATE TABLE IF NOT EXISTS `directorio_general` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tipo` enum('Presidencia','Retama') NOT NULL,
  `dependencia` varchar(100) NOT NULL,
  `rango` varchar(50) DEFAULT NULL,
  `nombre` varchar(50) NOT NULL,
  `ext` text DEFAULT NULL,
  `correo` varchar(50) DEFAULT NULL,
  `numerotelef` varchar(50) DEFAULT NULL,
  `edificio` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=127 DEFAULT CHARSET=utf8mb4;

INSERT INTO `directorio_general` (`id`, `tipo`, `dependencia`, `rango`, `nombre`, `ext`, `correo`, `numerotelef`, `edificio`) VALUES
	(1, 'Presidencia', 'Síndicos', 'Primer Síndico', 'Blanca Leticia Guzmán Hinojosa', '101', NULL, NULL, NULL),
	(2, 'Presidencia', 'Síndicos', 'Segundo Síndico', 'Ricardo Vega Barrón', '102', NULL, NULL, NULL),
	(3, 'Presidencia', 'Regidores', 'Primer Regidor', 'Diana Isabel Rangel Rangel', '135', NULL, NULL, NULL),
	(4, 'Presidencia', 'Regidores', 'Segundo Regidor', 'Bernardino Álvarez Cedillo', '136', NULL, NULL, NULL),
	(5, 'Presidencia', 'Regidores', 'Tercer Regidor', 'Damaris Oralia Gómez Cervantes', '137', NULL, NULL, NULL),
	(6, 'Presidencia', 'Regidores', 'Cuarto Regidor', 'Edgar Mauricio Medina Magaña', '133', NULL, NULL, NULL),
	(7, 'Presidencia', 'Regidores', 'Quinto Regidor', 'Nadia Flor Torres Martinez', '142', NULL, NULL, NULL),
	(8, 'Presidencia', 'Regidores', 'Sexto Regidor', 'Juan Francisco Guevara Barrón', '143', NULL, NULL, NULL),
	(9, 'Presidencia', 'Regidores', 'Septimo Regidor', 'Epifania Moran Villeda', '151', NULL, NULL, NULL),
	(10, 'Presidencia', 'Regidores', 'Octavo Regidor', 'José Ismael Mex Santiago', '152', NULL, NULL, NULL),
	(11, 'Presidencia', 'Regidores', 'Noveno Regidor', 'Martha Eladia Garcia Carrizales', '153', NULL, NULL, NULL),
	(12, 'Presidencia', 'Regidores', 'Decimo Regidor', 'Abelardo Garcés Reyes', '154', NULL, NULL, NULL),
	(13, 'Presidencia', 'Regidores', 'Decimo Primer Regidor', 'Ana Delia Zaleta Avalos', '155', NULL, NULL, NULL),
	(14, 'Presidencia', 'Regidores', 'Decimo Segundo Regidor', 'Luis Gabriel Márquez Gonzales', '153', NULL, NULL, NULL),
	(15, 'Presidencia', 'Regidores', 'Decimo Tercer Regidor', 'Naivi Aracely Castillo Diaz', '157', NULL, NULL, NULL),
	(16, 'Presidencia', 'Regidores', 'Decimo Cuarto Regidor', 'Azucena Ledezma Camacho', '158', NULL, NULL, NULL),
	(17, 'Presidencia', 'Regidores', 'Decimo Quinto Regidor', 'Nancy Ruiz Martínez', '159', NULL, NULL, NULL),
	(18, 'Presidencia', 'Regidores', 'Decimo Sexto Regidor', 'Leticia Barrios Chavero', '160', NULL, NULL, NULL),
	(19, 'Presidencia', 'Regidores', 'Decimo Septimo Regidor', 'Uriel Ulises Ponce García', '161', NULL, NULL, NULL),
	(20, 'Presidencia', 'Regidores', 'Decimo Octavo Regidor', 'Julio Salvador Alfaro Flores', '162', NULL, NULL, NULL),
	(21, 'Presidencia', 'Regidores', 'Decimo Noveno Regidor', 'Félix Miguel Guillu Meraz', '163', NULL, NULL, NULL),
	(22, 'Presidencia', 'Regidores', 'Vigesimo Regidor', 'Flor de Nubia Vázquez Chávez', '164', NULL, NULL, NULL),
	(23, 'Presidencia', 'Regidores', 'Vigesimo Primer Regidor', 'Octavio Moisés Jiménez Márquez', '166', NULL, NULL, NULL),
	(24, 'Presidencia', 'Secretaría Del Ayuntamiento', NULL, 'Jurídico', '126', NULL, NULL, NULL),
	(25, 'Presidencia', 'Secretaría Del Ayuntamiento', NULL, 'Subsecretaría', '134, 131', NULL, NULL, NULL),
	(26, 'Presidencia', 'Secretaría Del Ayuntamiento', NULL, 'Asistente Secretaría Particular', '110', NULL, NULL, NULL),
	(27, 'Presidencia', 'Secretaría Del Ayuntamiento', NULL, 'Secretaría Particular', '108', NULL, NULL, NULL),
	(29, 'Presidencia', 'Secretaría Del Ayuntamiento', NULL, 'Secretaría Del Ayuntamiento', '105', NULL, NULL, NULL),
	(30, 'Presidencia', 'Secretaría Del Ayuntamiento', NULL, 'Sala De Cabildo', '109', NULL, NULL, NULL),
	(31, 'Presidencia', 'Secretaría Del Ayuntamiento', NULL, 'Coordinación de Presidencia', '103', NULL, NULL, NULL),
	(32, 'Presidencia', 'Externos', NULL, 'Emergencias Bomberos', NULL, NULL, '8332644027', NULL),
	(33, 'Presidencia', 'Externos', NULL, 'Turismo', NULL, NULL, '8331621652', NULL),
	(34, 'Presidencia', 'Externos', NULL, 'Posco', '651, 652', NULL, NULL, NULL),
	(36, 'Presidencia', 'Externos', NULL, 'Delegación Zona Sur', NULL, NULL, '8334546185', NULL),
	(37, 'Presidencia', 'Externos', NULL, 'Delegación Z.S Atención Ciudadana', NULL, NULL, '8334546180', NULL),
	(38, 'Presidencia', 'Externos', NULL, 'Delegación Zona Norte', NULL, NULL, '8362760312', NULL),
	(39, 'Presidencia', 'Externos', NULL, 'Ingresos Zona Norte', NULL, NULL, '8362760538', NULL),
	(40, 'Presidencia', 'Externos', NULL, 'Registro Civil Zona Norte', NULL, NULL, '8362760362', NULL),
	(41, 'Presidencia', 'Externos', NULL, 'DIF Recepción', NULL, NULL, '8331621650', NULL),
	(42, 'Presidencia', 'Externos', NULL, 'Panteón Municipal', '503', NULL, NULL, NULL),
	(43, 'Presidencia', 'Externos', NULL, 'Preparatoria Municipal', NULL, NULL, '8334090058 , 8334090059', NULL),
	(44, 'Presidencia', 'Externos', NULL, 'Cultura', NULL, NULL, '8334580119', NULL),
	(45, 'Presidencia', 'Externos', NULL, 'Transito', NULL, NULL, '8332248685', NULL),
	(46, 'Presidencia', 'Externos', NULL, 'Emergencias Protección Civil', NULL, NULL, '8332646445', NULL),
	(47, 'Presidencia', 'Externos', NULL, 'Recepción Protección Civil', NULL, NULL, '8334730017', NULL),
	(48, 'Presidencia', 'Externos', NULL, 'Bomberos', NULL, NULL, '8331620162', NULL),
	(49, 'Presidencia', 'Externos', NULL, 'Obras Públicas', NULL, NULL, '8336888306', NULL),
	(50, 'Presidencia', 'Externos', NULL, 'Servicios Públicos', NULL, NULL, '8331622326', NULL),
	(51, 'Presidencia', 'Externos', NULL, 'Bienestar Animal', NULL, NULL, '8331753551', NULL),
	(64, 'Retama', 'Ingresos', NULL, 'Facturación', '438', NULL, NULL, 'E1 Planta Baja'),
	(65, 'Retama', 'Ingresos', NULL, 'Asistente Director', '439', NULL, NULL, 'E1 Planta Baja'),
	(66, 'Retama', 'Ingresos', NULL, 'Catastro Oficios', '440', NULL, NULL, 'E1 Planta Baja'),
	(67, 'Retama', 'Ingresos', NULL, 'Mercados Auxiliar', '488', NULL, NULL, 'E1 Planta Baja'),
	(68, 'Retama', 'Administración', NULL, 'Administración Recepción', '341', NULL, NULL, 'E1 Planta Baja'),
	(69, 'Retama', 'Tesorería', NULL, 'Recepción Tesorería', '215', NULL, NULL, 'E1 Planta Alta'),
	(70, 'Retama', 'Contraloría', NULL, 'Asistente Contraloría', '444', NULL, NULL, 'E1 Planta Alta'),
	(71, 'Retama', 'Contraloría', NULL, 'Recepción Contraloría', '445', NULL, NULL, 'E1 Planta Alta'),
	(72, 'Retama', 'Contraloría', NULL, 'Proveedores', '487', NULL, NULL, 'E1 Planta Alta'),
	(73, 'Retama', 'Contraloría', NULL, 'Parque Vehicular', '477', NULL, NULL, 'E1 Planta Alta'),
	(74, 'Retama', 'Contraloría', NULL, 'Coordinación Inventarios', '465', NULL, NULL, 'E1 Planta Alta'),
	(75, 'Retama', 'Desarrollo Económico', NULL, 'Recepción Desarrollo Económico', '441', NULL, NULL, 'E2 Planta Baja'),
	(76, 'Retama', 'Desarrollo Económico', NULL, 'Asesoría a MYPES', '227', NULL, NULL, 'E2 Planta Baja'),
	(77, 'Retama', 'Desarrollo Económico', NULL, 'Coordinación Administrativa', '204', NULL, NULL, 'E2 Planta Baja'),
	(78, 'Retama', 'Desarrollo Económico', NULL, 'Coordinación de Planeación', '205', NULL, NULL, 'E2 Planta Baja'),
	(79, 'Retama', 'Desarrollo Económico', NULL, 'Jefatura Jurídica', '203', NULL, NULL, 'E2 Planta Baja'),
	(80, 'Retama', 'Desarrollo Económico', NULL, 'Enlace Administrativo', '202', NULL, NULL, 'E2 Planta Baja'),
	(81, 'Retama', 'Desarrollo Económico', NULL, 'Coordinación de Gestión', '226', NULL, NULL, 'E2 Planta Baja'),
	(82, 'Retama', 'Desarrollo Económico', NULL, 'Coordinación de Sectores Productivos', '207', NULL, NULL, 'E2 Planta Baja'),
	(83, 'Retama', 'Desarrollo Económico', NULL, 'Jefatura Gestión Empresarial', '208', NULL, NULL, 'E2 Planta Baja'),
	(84, 'Retama', 'Desarrollo Económico', NULL, 'Jefatura de Proyectos y Energía', '206', NULL, NULL, 'E2 Planta Baja'),
	(85, 'Retama', 'Atención A La Mujer', NULL, 'Instituto Municipal a la Mujer', NULL, NULL, '8334039655', 'E2 Planta Baja'),
	(86, 'Retama', 'Programas Sociales', NULL, 'Coordinación Programas Sociales', '225', NULL, NULL, 'E2 Planta Baja'),
	(87, 'Retama', 'Programas Federales Y Estatales', NULL, 'INAPAM', '237', NULL, NULL, 'E2 Planta Baja'),
	(88, 'Retama', 'Programas Federales Y Estatales', NULL, 'Trabajo Social', '213', NULL, NULL, 'E2 Planta Baja'),
	(89, 'Retama', 'Programas Federales Y Estatales', NULL, 'Coordinación de Programas Sociales', '225', NULL, NULL, 'E2 Planta Baja'),
	(90, 'Retama', 'Programas Federales Y Estatales', NULL, 'Jefatura de Programas Federales', '240', NULL, NULL, 'E2 Planta Baja'),
	(91, 'Retama', 'Programas Federales Y Estatales', NULL, 'Administrativo Programas Federales y Estatales', '251', NULL, NULL, 'E2 Planta Baja'),
	(92, 'Retama', 'Educación', NULL, 'Recepción Educación', '231', NULL, NULL, 'E2 Planta Alta'),
	(93, 'Retama', 'Educación', NULL, 'Becas', '232', NULL, NULL, 'E2 Planta Alta'),
	(94, 'Retama', 'Educación', NULL, 'Administrativo Educación', '234,236', NULL, NULL, 'E2 Planta Alta'),
	(96, 'Retama', 'Atención  A La Juventud', NULL, 'Recepción Atención a la Juventud', '224', NULL, NULL, 'E2 Planta Alta'),
	(97, 'Retama', 'Atención  A La Juventud', NULL, 'Atención a la Juventud', '242', NULL, NULL, 'E2 Planta Alta'),
	(98, 'Retama', 'Coordinación De Gestion Social', NULL, 'Izza María Morales Martínez', NULL, NULL, '8332639627', 'E2 Planta Alta'),
	(99, 'Retama', 'Bienestar Social', NULL, 'Recepción Bienestar Social', '210', NULL, NULL, 'E2 Planta Alta'),
	(100, 'Retama', 'Bienestar Social', NULL, 'Salud', '228', NULL, NULL, 'E2 Planta Alta'),
	(101, 'Retama', 'Bienestar Social', NULL, 'Bienestar Social', '217', NULL, NULL, 'E2 Planta Alta'),
	(102, 'Retama', 'Bienestar Social', NULL, 'Jefatura de Programas Municipales', '243', NULL, NULL, 'E2 Planta Alta'),
	(103, 'Retama', 'Bienestar Social', NULL, 'Asistente Bienestar Social', '247', NULL, NULL, 'E2 Planta Alta'),
	(104, 'Retama', 'Bienestar Social', NULL, 'Coordinación Operativa', '241', NULL, NULL, 'E2 Planta Alta'),
	(105, 'Retama', 'Bienestar Social', NULL, 'Coordinación Equidad y Género', '238', NULL, NULL, 'E2 Planta Alta'),
	(106, 'Retama', 'Recursos Humanos', NULL, 'RH. Recepcíon', '351', NULL, NULL, 'E3 Planta Baja'),
	(107, 'Retama', 'Recursos Humanos', NULL, 'RH. Administrativo', '349', NULL, NULL, 'E3 Planta Baja'),
	(108, 'Retama', 'Sistemas', NULL, 'Recepción Sistemas', '360', NULL, NULL, 'E3 Planta Baja'),
	(109, 'Retama', 'Sistemas', NULL, 'Soporte', '363', NULL, NULL, 'E3 Planta Baja'),
	(110, 'Retama', 'Sistemas', NULL, 'Gobierno Digital', '365', NULL, NULL, 'E3 Planta Baja'),
	(111, 'Retama', 'Sistemas', NULL, 'Telecom', '361', NULL, NULL, 'E3 Planta Baja'),
	(112, 'Retama', 'Sistemas', NULL, 'Sistemas Presidencia', '121', NULL, NULL, 'E3 Planta Baja'),
	(113, 'Retama', 'Desarrollo Urbano', NULL, 'Asistente Desarrollo Urbano', '344', NULL, NULL, 'E3 Planta Baja'),
	(114, 'Retama', 'Desarrollo Urbano', NULL, 'Ventanilla Desarrollo Urbano', '340', NULL, NULL, 'E3 Planta Baja'),
	(115, 'Retama', 'Desarrollo Urbano', NULL, 'Juridico', '364', NULL, NULL, 'E3 Planta Baja'),
	(116, 'Retama', 'Desarrollo Urbano', NULL, 'Area Operativa', '366', NULL, NULL, 'E3 Planta Baja'),
	(117, 'Retama', 'Desarrollo Urbano', NULL, 'Archivo', '343', NULL, NULL, 'E3 Planta Baja'),
	(118, 'Retama', 'Servicios Generales', NULL, 'Coordinación Servicios Generales', '356', NULL, NULL, 'E3 Planta Alta'),
	(119, 'Retama', 'Ecologia Y Medio Ambiente', NULL, 'Recepción Ecologia', '403', NULL, NULL, 'E3 Planta Alta'),
	(120, 'Retama', 'Dirección Tecnica', NULL, 'Recepción Dirección Tecnica', '321', NULL, NULL, 'E3 Planta Alta'),
	(121, 'Retama', 'Dirección Tecnica', NULL, 'Manual Operativo', '405', NULL, NULL, 'E3 Planta Alta'),
	(122, 'Retama', 'Dirección Tecnica', NULL, 'Programas', '320', NULL, NULL, 'E3 Planta Alta'),
	(123, 'Retama', 'Comunicación Social', NULL, 'Recepción de Comunicación Social', '330', NULL, NULL, 'E3 Planta Alta');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
